import os

SQLALCHEMY_DATABASE_URI = 'sqlite:///database/heatstroke.db'
SQLALCHEMY_TRACK_MODIFICATIONS = True

LINE_CHANNEL_ACCESS_TOKEN = os.environ['LINE_CHANNEL_ACCESS_TOKEN']
LINE_CHANNEL_SECRET = os.environ['LINE_CHANNEL_SECRET']

DEBUG = True
